/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expo.ui;

import expo.controller.ConfirmarRegistoUtilizadorController;
import expo.model.CentroExposicoes;
import expo.model.Utilizador;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Nuno
 */
public class ConfirmarRegistoUtilizadorUI extends javax.swing.JFrame {

    private CentroExposicoes ce;
    private Utilizador uti;
    private ConfirmarRegistoUtilizadorController controller;
    
    /**
     * Creates new form ConfirmarRegistoUtilizadorUI
     */
    public ConfirmarRegistoUtilizadorUI(CentroExposicoes ce, Utilizador uti) {
        this.ce = ce;
        this.uti = uti;
        this.controller = new ConfirmarRegistoUtilizadorController(ce);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArrayList<Utilizador> lista = (ArrayList) controller.iniciaConfirmacaoUtilizador();

        if(lista.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Não existem utilizadores a aguardar confirmação.", "Erro", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
        lista_utiParaConfirm = new javax.swing.JList<>();
        ajuda_bt = new javax.swing.JButton();
        confirmar_bt = new javax.swing.JButton();
        concluido_bt = new javax.swing.JButton();
        remover_bt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/confirm_user.png"))); // NOI18N
        jLabel1.setText("   Confirmar Utilizadores");
        jLabel1.setToolTipText("");

        jScrollPane1.setViewportView(lista_utiParaConfirm);

        ajuda_bt.setBorderPainted(false);
        ajuda_bt.setContentAreaFilled(false);
        ajuda_bt.setFocusPainted(false);
        ajuda_bt.setOpaque(false);
        ajuda_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/help.png"))); // NOI18N

        confirmar_bt.setText("Confirmar");
        confirmar_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmar_btActionPerformed(evt);
            }
        });

        concluido_bt.setText("Concluído");
        concluido_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluido_btActionPerformed(evt);
            }
        });

        remover_bt.setText("Remover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ajuda_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmar_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(concluido_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(remover_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ajuda_bt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmar_bt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(remover_bt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(concluido_bt)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void concluido_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluido_btActionPerformed
        dispose();
    }//GEN-LAST:event_concluido_btActionPerformed

    private void confirmar_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmar_btActionPerformed
        int index = this.lista_utiParaConfirm.getSelectedIndex();
        Utilizador uti = controller.iniciaConfirmacaoUtilizador().get(index);
        controller.getUtilizadorInfo(uti.getUsername());
        controller.confirmaRegistoUtilizador();
    }//GEN-LAST:event_confirmar_btActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ConfirmarRegistoUtilizadorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ConfirmarRegistoUtilizadorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ConfirmarRegistoUtilizadorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ConfirmarRegistoUtilizadorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ConfirmarRegistoUtilizadorUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajuda_bt;
    private javax.swing.JButton concluido_bt;
    private javax.swing.JButton confirmar_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista_utiParaConfirm;
    private javax.swing.JButton remover_bt;
    // End of variables declaration//GEN-END:variables
}
